// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGP2XQUNG6gdGkS78m8mhJfS7ViduNeI',
    appId: '1:258207594608:web:a1cfa0769d337eaebf5cb5',
    messagingSenderId: '258207594608',
    projectId: 'al-akbar-452b4',
    authDomain: 'al-akbar-452b4.firebaseapp.com',
    storageBucket: 'al-akbar-452b4.firebasestorage.app',
    measurementId: 'G-Y1P86MN7NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoTId9_5BaN79rTZlWhgehR1gwyRYWm-4',
    appId: '1:258207594608:android:46e284e97c360e91bf5cb5',
    messagingSenderId: '258207594608',
    projectId: 'al-akbar-452b4',
    storageBucket: 'al-akbar-452b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpKQ2laatrX70ugkS7Vj4gboeGNt2iYbE',
    appId: '1:258207594608:ios:49dfb5099b583310bf5cb5',
    messagingSenderId: '258207594608',
    projectId: 'al-akbar-452b4',
    storageBucket: 'al-akbar-452b4.firebasestorage.app',
    androidClientId: '258207594608-8tplf41p1vfdnifd8b4s7h2vjp0eajn0.apps.googleusercontent.com',
    iosClientId: '258207594608-9pb2sq0889358egqltbd6bt1jn8do5pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaunkingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpKQ2laatrX70ugkS7Vj4gboeGNt2iYbE',
    appId: '1:258207594608:ios:49dfb5099b583310bf5cb5',
    messagingSenderId: '258207594608',
    projectId: 'al-akbar-452b4',
    storageBucket: 'al-akbar-452b4.firebasestorage.app',
    androidClientId: '258207594608-8tplf41p1vfdnifd8b4s7h2vjp0eajn0.apps.googleusercontent.com',
    iosClientId: '258207594608-9pb2sq0889358egqltbd6bt1jn8do5pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaunkingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFGP2XQUNG6gdGkS78m8mhJfS7ViduNeI',
    appId: '1:258207594608:web:310949a13cb90f79bf5cb5',
    messagingSenderId: '258207594608',
    projectId: 'al-akbar-452b4',
    authDomain: 'al-akbar-452b4.firebaseapp.com',
    storageBucket: 'al-akbar-452b4.firebasestorage.app',
    measurementId: 'G-RWRYH8SWCV',
  );
}
